version: '3.8'

services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - musicstream_net
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
      MINIO_ENDPOINT: minio
      MINIO_PORT: ${MINIO_PORT}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      HOST: ${HOST}
      CRYPTOGRAPHY_KEY: ${CRYPTOGRAPHY_KEY}
    depends_on:
      - ws
      - minio

  ws:
    build:
      context: wsocket
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      SOCKET_SERVER: ${SOCKET_SERVER}
      SOCKET_SERVER_PORT: ${SOCKET_SERVER_PORT}
    depends_on:
      - minio

  minio:
      image: minio/minio:latest
      command: server --console-address ":9010" /minio/data
      ports:
        - "9000:9000"
        - "9010:9010"
      networks:
        - musicstream_net
      healthcheck:
        test: ["CMD","curl","-f","http://localhost:9010/minio/health/live"]
        interval: 30s
        timeout: 20s
        retries: 3
      environment:
        MINIO_ROOT_USER: ${MINIO_ROOT_USER}
        MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      volumes:
        - /Users/abolfazlsaeidi/Documents/minio/data:/data
        - /Users/abolfazlsaeidi/Documents/minio/config:/root/.minio

networks:
  musicstream_net:
    name: musicstream_net